# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chord_pb2 as chord__pb2


class chordStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Noop = channel.unary_unary(
        '/chord.chord/Noop',
        request_serializer=chord__pb2.Null.SerializeToString,
        response_deserializer=chord__pb2.Null.FromString,
        )
    self.Reset = channel.unary_unary(
        '/chord.chord/Reset',
        request_serializer=chord__pb2.Null.SerializeToString,
        response_deserializer=chord__pb2.Null.FromString,
        )
    self.Put = channel.unary_unary(
        '/chord.chord/Put',
        request_serializer=chord__pb2.PutRequest.SerializeToString,
        response_deserializer=chord__pb2.PutResponse.FromString,
        )
    self.DirectPut = channel.unary_unary(
        '/chord.chord/DirectPut',
        request_serializer=chord__pb2.DirectPutRequest.SerializeToString,
        response_deserializer=chord__pb2.DirectPutResponse.FromString,
        )
    self.DirectPutMulti = channel.unary_unary(
        '/chord.chord/DirectPutMulti',
        request_serializer=chord__pb2.DirectPutMultiRequest.SerializeToString,
        response_deserializer=chord__pb2.DirectPutMultiResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/chord.chord/Get',
        request_serializer=chord__pb2.GetRequest.SerializeToString,
        response_deserializer=chord__pb2.GetResponse.FromString,
        )
    self.GetReplicas = channel.unary_unary(
        '/chord.chord/GetReplicas',
        request_serializer=chord__pb2.GetReplicasRequest.SerializeToString,
        response_deserializer=chord__pb2.GetReplicasResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/chord.chord/Delete',
        request_serializer=chord__pb2.DeleteRequest.SerializeToString,
        response_deserializer=chord__pb2.DeleteResponse.FromString,
        )
    self.GetRange = channel.unary_unary(
        '/chord.chord/GetRange',
        request_serializer=chord__pb2.GetRangeRequest.SerializeToString,
        response_deserializer=chord__pb2.GetRangeResponse.FromString,
        )
    self.DeleteRange = channel.unary_unary(
        '/chord.chord/DeleteRange',
        request_serializer=chord__pb2.DeleteRangeRequest.SerializeToString,
        response_deserializer=chord__pb2.DeleteRangeResponse.FromString,
        )
    self.Notify = channel.unary_unary(
        '/chord.chord/Notify',
        request_serializer=chord__pb2.NotifyRequest.SerializeToString,
        response_deserializer=chord__pb2.NotifyResponse.FromString,
        )
    self.Leave = channel.unary_unary(
        '/chord.chord/Leave',
        request_serializer=chord__pb2.Null.SerializeToString,
        response_deserializer=chord__pb2.Null.FromString,
        )
    self.Resume = channel.unary_unary(
        '/chord.chord/Resume',
        request_serializer=chord__pb2.ResumeRequest.SerializeToString,
        response_deserializer=chord__pb2.ResumeResponse.FromString,
        )
    self.GetSuccessor = channel.unary_unary(
        '/chord.chord/GetSuccessor',
        request_serializer=chord__pb2.GetSuccessorRequest.SerializeToString,
        response_deserializer=chord__pb2.GetSuccessorResponse.FromString,
        )
    self.GetSuccessorList = channel.unary_unary(
        '/chord.chord/GetSuccessorList',
        request_serializer=chord__pb2.Null.SerializeToString,
        response_deserializer=chord__pb2.GetSuccessorListResponse.FromString,
        )
    self.GetPredecessor = channel.unary_unary(
        '/chord.chord/GetPredecessor',
        request_serializer=chord__pb2.Null.SerializeToString,
        response_deserializer=chord__pb2.GetPredecessorResponse.FromString,
        )
    self.GetFingers = channel.unary_unary(
        '/chord.chord/GetFingers',
        request_serializer=chord__pb2.Null.SerializeToString,
        response_deserializer=chord__pb2.GetFingersResponse.FromString,
        )
    self.UploadConfig = channel.unary_unary(
        '/chord.chord/UploadConfig',
        request_serializer=chord__pb2.UploadConfigRequest.SerializeToString,
        response_deserializer=chord__pb2.UploadConfigResponse.FromString,
        )
    self.GetStatus = channel.unary_unary(
        '/chord.chord/GetStatus',
        request_serializer=chord__pb2.Null.SerializeToString,
        response_deserializer=chord__pb2.GetStatusResponse.FromString,
        )
    self.DoReplicate = channel.unary_unary(
        '/chord.chord/DoReplicate',
        request_serializer=chord__pb2.DoReplicateRequest.SerializeToString,
        response_deserializer=chord__pb2.DoReplicateResponse.FromString,
        )
    self.UpdateReplica = channel.unary_unary(
        '/chord.chord/UpdateReplica',
        request_serializer=chord__pb2.UpdateReplicaRequest.SerializeToString,
        response_deserializer=chord__pb2.UpdateReplicaResponse.FromString,
        )


class chordServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Noop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DirectPut(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DirectPutMulti(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetReplicas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Notify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Leave(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Resume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSuccessor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSuccessorList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPredecessor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFingers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoReplicate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateReplica(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_chordServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Noop': grpc.unary_unary_rpc_method_handler(
          servicer.Noop,
          request_deserializer=chord__pb2.Null.FromString,
          response_serializer=chord__pb2.Null.SerializeToString,
      ),
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=chord__pb2.Null.FromString,
          response_serializer=chord__pb2.Null.SerializeToString,
      ),
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=chord__pb2.PutRequest.FromString,
          response_serializer=chord__pb2.PutResponse.SerializeToString,
      ),
      'DirectPut': grpc.unary_unary_rpc_method_handler(
          servicer.DirectPut,
          request_deserializer=chord__pb2.DirectPutRequest.FromString,
          response_serializer=chord__pb2.DirectPutResponse.SerializeToString,
      ),
      'DirectPutMulti': grpc.unary_unary_rpc_method_handler(
          servicer.DirectPutMulti,
          request_deserializer=chord__pb2.DirectPutMultiRequest.FromString,
          response_serializer=chord__pb2.DirectPutMultiResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=chord__pb2.GetRequest.FromString,
          response_serializer=chord__pb2.GetResponse.SerializeToString,
      ),
      'GetReplicas': grpc.unary_unary_rpc_method_handler(
          servicer.GetReplicas,
          request_deserializer=chord__pb2.GetReplicasRequest.FromString,
          response_serializer=chord__pb2.GetReplicasResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=chord__pb2.DeleteRequest.FromString,
          response_serializer=chord__pb2.DeleteResponse.SerializeToString,
      ),
      'GetRange': grpc.unary_unary_rpc_method_handler(
          servicer.GetRange,
          request_deserializer=chord__pb2.GetRangeRequest.FromString,
          response_serializer=chord__pb2.GetRangeResponse.SerializeToString,
      ),
      'DeleteRange': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRange,
          request_deserializer=chord__pb2.DeleteRangeRequest.FromString,
          response_serializer=chord__pb2.DeleteRangeResponse.SerializeToString,
      ),
      'Notify': grpc.unary_unary_rpc_method_handler(
          servicer.Notify,
          request_deserializer=chord__pb2.NotifyRequest.FromString,
          response_serializer=chord__pb2.NotifyResponse.SerializeToString,
      ),
      'Leave': grpc.unary_unary_rpc_method_handler(
          servicer.Leave,
          request_deserializer=chord__pb2.Null.FromString,
          response_serializer=chord__pb2.Null.SerializeToString,
      ),
      'Resume': grpc.unary_unary_rpc_method_handler(
          servicer.Resume,
          request_deserializer=chord__pb2.ResumeRequest.FromString,
          response_serializer=chord__pb2.ResumeResponse.SerializeToString,
      ),
      'GetSuccessor': grpc.unary_unary_rpc_method_handler(
          servicer.GetSuccessor,
          request_deserializer=chord__pb2.GetSuccessorRequest.FromString,
          response_serializer=chord__pb2.GetSuccessorResponse.SerializeToString,
      ),
      'GetSuccessorList': grpc.unary_unary_rpc_method_handler(
          servicer.GetSuccessorList,
          request_deserializer=chord__pb2.Null.FromString,
          response_serializer=chord__pb2.GetSuccessorListResponse.SerializeToString,
      ),
      'GetPredecessor': grpc.unary_unary_rpc_method_handler(
          servicer.GetPredecessor,
          request_deserializer=chord__pb2.Null.FromString,
          response_serializer=chord__pb2.GetPredecessorResponse.SerializeToString,
      ),
      'GetFingers': grpc.unary_unary_rpc_method_handler(
          servicer.GetFingers,
          request_deserializer=chord__pb2.Null.FromString,
          response_serializer=chord__pb2.GetFingersResponse.SerializeToString,
      ),
      'UploadConfig': grpc.unary_unary_rpc_method_handler(
          servicer.UploadConfig,
          request_deserializer=chord__pb2.UploadConfigRequest.FromString,
          response_serializer=chord__pb2.UploadConfigResponse.SerializeToString,
      ),
      'GetStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatus,
          request_deserializer=chord__pb2.Null.FromString,
          response_serializer=chord__pb2.GetStatusResponse.SerializeToString,
      ),
      'DoReplicate': grpc.unary_unary_rpc_method_handler(
          servicer.DoReplicate,
          request_deserializer=chord__pb2.DoReplicateRequest.FromString,
          response_serializer=chord__pb2.DoReplicateResponse.SerializeToString,
      ),
      'UpdateReplica': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateReplica,
          request_deserializer=chord__pb2.UpdateReplicaRequest.FromString,
          response_serializer=chord__pb2.UpdateReplicaResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chord.chord', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
